# n8n
# Automation System

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "2007:5678"
    environment:
      - PUID: 1000
      - GUID: 1000
      - GENERIC_TIMEZONE=America/Chicago
      - TZ=America/Chicago
    volumes:
      - n8n:/home/node/.n8n

volumes:
  n8n:
