# Portainer Compose
# The 2.20.2 version is needed because the new docker version requires a new API.


services:
  portainer:
    image: portainer/portainer-ce:2.20.2
    container_name: portainer
    restart: always
    ports:
      - "9443:9443"
      - "8000:8000"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data
